### Register User
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "maddy2",
  "email": "maddy2@example.com",
  "password": "123456",
  "totp": "mysecret123",
  "qotp": "backup123"
}

### Login User
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "maddy2@example.com",
  "password": "123456"
}
